baseURL = ""
languageCode = "en"
DefaultContentLanguage = "en"
title = "PlushArtLab"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
profilePicture = "images/pal-teddybear.jpg"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-68131029-1"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true